import type { Activity } from "./types"

export const ACTIVITIES: Activity[] = [
  {
    id: "1",
    name: "Brunch at Local Cafe",
    category: "food",
    duration: 2,
    description: "Enjoy a leisurely brunch with friends at a cozy local cafe",
    image: "/cozy-cafe-brunch.jpg",
    mood: "social",
    cost: "medium",
    timeOfDay: "morning",
    location: {
      name: "The Cozy Corner Cafe",
      address: "123 Main St, Downtown",
      lat: 40.7128,
      lng: -74.006,
    },
  },
  {
    id: "2",
    name: "Hiking Trail Adventure",
    category: "outdoor",
    duration: 4,
    description: "Explore scenic hiking trails and connect with nature",
    image: "/mountain-hiking-trail.png",
    mood: "adventurous",
    cost: "free",
    timeOfDay: "morning",
    location: {
      name: "Sunset Ridge Trail",
      address: "Mountain View Park",
      lat: 40.7589,
      lng: -73.9851,
    },
  },
  {
    id: "3",
    name: "Movie Night at Home",
    category: "entertainment",
    duration: 3,
    description: "Cozy movie marathon with popcorn and blankets",
    image: "/cozy-movie-night-setup.jpg",
    mood: "relaxed",
    cost: "low",
    timeOfDay: "evening",
  },
  {
    id: "4",
    name: "Yoga in the Park",
    category: "wellness",
    duration: 1.5,
    description: "Peaceful outdoor yoga session to center yourself",
    image: "/outdoor-yoga-in-park.jpg",
    mood: "relaxed",
    cost: "free",
    timeOfDay: "morning",
    location: {
      name: "Riverside Park",
      address: "789 Park Ave, Riverside",
      lat: 40.7505,
      lng: -73.9934,
    },
  },
  {
    id: "5",
    name: "Art Museum Visit",
    category: "culture",
    duration: 3,
    description: "Explore contemporary art exhibitions and installations",
    image: "/modern-art-museum-gallery.jpg",
    mood: "social",
    cost: "medium",
    timeOfDay: "afternoon",
    location: {
      name: "Metropolitan Art Museum",
      address: "456 Culture Ave",
      lat: 40.7794,
      lng: -73.9632,
    },
  },
  {
    id: "6",
    name: "Farmers Market Shopping",
    category: "social",
    duration: 2,
    description: "Browse fresh produce and local crafts at the weekend market",
    image: "/vibrant-farmers-market.jpg",
    mood: "social",
    cost: "medium",
    timeOfDay: "morning",
    location: {
      name: "Union Square Farmers Market",
      address: "Union Square, Manhattan",
      lat: 40.7359,
      lng: -73.9911,
    },
  },
  {
    id: "7",
    name: "Beach Day Relaxation",
    category: "outdoor",
    duration: 6,
    description: "Spend the day soaking up sun and enjoying ocean waves",
    image: "/sunny-beach-day.jpg",
    mood: "relaxed",
    cost: "low",
    timeOfDay: "any",
    location: {
      name: "Coney Island Beach",
      address: "Coney Island, Brooklyn, NY",
      lat: 40.5755,
      lng: -73.9707,
    },
  },
  {
    id: "8",
    name: "Cooking Class",
    category: "food",
    duration: 3,
    description: "Learn to cook a new cuisine with expert instruction",
    image: "/cooking-class-kitchen.png",
    mood: "social",
    cost: "high",
    timeOfDay: "afternoon",
    location: {
      name: "Culinary Institute Downtown",
      address: "321 Chef St, Culinary District",
      lat: 40.7282,
      lng: -74.0776,
    },
  },
  {
    id: "9",
    name: "Live Music Concert",
    category: "entertainment",
    duration: 4,
    description: "Experience live music from local and touring artists",
    image: "/live-music-concert-venue.jpg",
    mood: "energetic",
    cost: "high",
    timeOfDay: "evening",
    location: {
      name: "Madison Square Garden",
      address: "4 Pennsylvania Plaza, New York, NY",
      lat: 40.7505,
      lng: -73.9934,
    },
  },
  {
    id: "10",
    name: "Spa Day at Home",
    category: "wellness",
    duration: 4,
    description: "Create a relaxing spa experience with DIY treatments",
    image: "/home-spa-relaxation.jpg",
    mood: "relaxed",
    cost: "low",
    timeOfDay: "afternoon",
  },
]

export const WEEKEND_THEMES = [
  {
    id: "lazy",
    name: "Lazy Weekend",
    description: "Perfect for recharging with low-key, relaxing activities",
    color: "bg-blue-100 text-blue-800",
    icon: "😴",
    suggestedActivities: ["3", "4", "7", "10"],
  },
  {
    id: "adventurous",
    name: "Adventure Seeker",
    description: "High-energy activities for thrill seekers",
    color: "bg-orange-100 text-orange-800",
    icon: "🏔️",
    suggestedActivities: ["2", "7", "9"],
  },
  {
    id: "family",
    name: "Family Fun",
    description: "Activities perfect for spending quality time with loved ones",
    color: "bg-green-100 text-green-800",
    icon: "👨‍👩‍👧‍👦",
    suggestedActivities: ["1", "5", "6"],
  },
  {
    id: "cultural",
    name: "Culture Explorer",
    description: "Immerse yourself in arts, history, and local culture",
    color: "bg-purple-100 text-purple-800",
    icon: "🎭",
    suggestedActivities: ["5", "8", "9"],
  },
]
